# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='vpc_id',
            field=models.CharField(blank=True, help_text='VPC ID', max_length=100, null=True, verbose_name='VPC ID'),
        ),
    ]
