# Generated by Django 6.0.2 on 2026-02-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0005_populate_instance_vpc'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instance',
            new_name='instances_i_account_0d65a4_idx',
            old_name='instances_i_account_idx',
        ),
        migrations.RenameIndex(
            model_name='instance',
            new_name='instances_i_state_f84c03_idx',
            old_name='instances_i_state_idx',
        ),
        migrations.RenameIndex(
            model_name='instance',
            new_name='instances_i_create__4d3347_idx',
            old_name='instances_i_create_t_idx',
        ),
    ]
