# Generated by Django 6.0.2 on 2026-02-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vpc',
            new_name='vpc_vpc_account_6d0542_idx',
            old_name='vpc_vpc_account_region_idx',
        ),
        migrations.RenameIndex(
            model_name='vpc',
            new_name='vpc_vpc_vpc_id_23909e_idx',
            old_name='vpc_vpc_vpc_id_idx',
        ),
    ]
